module.exports.login_Sevices = require("./Login_services")
module.exports.signup_Services = require("./Signup_services")
module.exports.shipping_Services = require("./Shipping_services")
module.exports.admin_Services = require("./admin_services")
module.exports.cart_Services = require('./cartServies')